app:
  jwt:
    secret: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFighting
    header-scheme-name: authorization
    token-type: Bearer
    access-token-expiry: 7200000
    refresh-token-expiry: 1296000000


file:
  dir: D:/gogi/download/gogiro/

api:
  comp:
    code:
      base-url: "https://api.odcloud.kr/api/nts-businessman/v1/status"
      service-code-key: "serviceKey"
      service-code-value: "cTMeBlOCpl%2FaaF%2BJTXLf40PU8Rv4Vkk2B%2FwyPitJSU0J%2FIYEOJxHltgmJhbiTYJOFOTcQ03I8fybIV8QKvM9hA%3D%3D"



spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.144:3306/db_even_last_1
    username: even_last_1
    password: army

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html


server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: "jpa"
  datasource:
    url: jdbc:mariadb://192.168.0.161:3306/test4
    username: root
    password: green502
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    generate-ddl: true


---


---


spring:
  config:
    activate:
      on-profile: "prod"


file:
  dir: /home/download/